name: kawena
favicon: null
layout_spectrum: 0.98981
typography_spectrum: 0.3185862326063216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eedbcd'
    - '#97c9c8'
    - '#60b1c6'
    - '#728faf'
    - '#5e6f81'
  brandStrength: 0.6875
  lightness: 0.9579914188943803
  saturation: 0.2706317091360688
  rhythmicContrast: 0.48695891723036766
purpose: []
